WIP: Advanced TM validation
thingweb/thingweb-playground pull request #383
Opened 2022-11-17 14:29 UTC by fatadel

Relates to #364

2022-11-17 15:10 UTC, egekorkan commented on packages/core/shared.js
> +            return false;
should be report as well

2022-12-19 10:14 UTC, egekorkan requested changes
There are two assertions to check for tm:optional:
- thing-model-td-generation-processor-type : All required interactions (not listed in tm:optional) MUST be taken over to the Partial TD instance. 
  - This should pass if there is no tm:optional as well.
  - This cannot be not-impl
- thing-model-td-generation-processor-optional : All optional interactions (listed in tm:optional) MAY be taken over to the Partial TD instance. 
  - At least one optional affordance in the TD means this is a pass.
  - If TD does not have any of the optional, this is a not-impl
  - This cannot fail

2022-12-20 14:49 UTC, fatadel commented on packages/cli/index.js
> +    tdValidator(td, console.log, {
No, since this is the only statement inside `checkTd` function, plus there is already `then`.

2022-12-20 15:00 UTC, fatadel commented
> There are two assertions to check for tm:optional:
> 
> * thing-model-td-generation-processor-type : All required interactions (not listed in tm:optional) MUST be taken over to the Partial TD instance.
>   
>   * This should pass if there is no tm:optional as well.
>   * This cannot be not-impl
> * thing-model-td-generation-processor-optional : All optional interactions (listed in tm:optional) MAY be taken over to the Partial TD instance.
>   
>   * At least one optional affordance in the TD means this is a pass.
>   * If TD does not have any of the optional, this is a not-impl
>   * This cannot fail

I guess the first one can be `not-impl` when td does not link to tm, right?

2022-12-20 20:18 UTC, egekorkan commented
> I guess the first one can be not-impl when td does not link to tm, right?

That's actually correct

2022-12-21 00:09 UTC, egekorkan commented
Just tried the Netlify preview and there is an error in the console.log:

> Uncaught (in promise) TypeError: can't convert undefined to object
    checkLinkedAffordances https://deploy-preview-383--playground-testing.netlify.app/node_modules/@thing-description-playground/core/dist/web-bundle.min.js:59
web-bundle.min.js:59:160242

The bigger problem is that, even with this error, the TM based validation succeeds. I will try on my local machine tomorrow.

2022-12-21 10:01 UTC, egekorkan requested changes

2022-12-21 10:01 UTC, egekorkan commented on packages/core/shared.js
> +        if (!isSubset(Object.keys(td[affordanceType]), required) && !requiredAssertion) {
Here I get:

       

>  if (!isSubset(Object.keys(td[affordanceType]), required) && !requiredAssertion) {
>                              ^
> 
> TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at Object.checkLinkedAffordances (/home/eko/git/thingweb-playground/packages/core/shared.js:1087:30)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async /home/eko/git/thingweb-playground/packages/core/index.js:178:59
> 
> Node.js v19.2.0

The object keys actual get logged correctly when I put add console.log statements so I am not sure where the error comes from

2022-12-21 10:02 UTC, egekorkan commented on packages/core/shared.js
> +    const requiredAssertion = false;
these cannot be const as well, they get reassigned

2022-12-22 15:45 UTC, egekorkan commented
There is something not working. [This TD](https://deploy-preview-383--playground-testing.netlify.app/#C4EwVgzg9gdg3gKAAQqQIgJYjQLnQVwCcYcIMBbABwBsBTNAGmVTQAEBjWYWgD2F3QALYMEoQcAegkB3WQDppAZjlRCAcwkAmAAybNMqMAmgJANwCMc842Yo0wDMDoC0AWQCeAGQCGVACqCGDBqNqjoILQQ7IQYlA6wLgBq3tRYSH4AIkiclBi0IEgAZoRQ5EjAgrRIEJS07ADkEEUYhBDASLy+NPRMYWgQdUSO7hm0hUGOGLAQAohhfQBG3mTsAPpRs7bzfVGV5PR4aEsrodvzmDAuld4RhGhbYQC+W4+9LAPsQ8DuAgDaDyxjhg1hstgBdN52SglWqEByRTZndBtbzAfAzPBzJEsb61FxtGLBU7Y9CFVTkDFIf4k7ZYmlnNCCQhjK4iMSSCTkdzULpyTpUOhyTjkCQotEzSH085QSh-AFS87Mm7QmW0OE-SUK7ZoaQxbgq2Hfe5a+YQ+VStCcGDca1+dx4w7eSg0YGoqYwCSQBLmpHPelm+loKALAaEUzeBbOPCFFIDTUMpUgADyMGoP2jsdo8e1usctBTaYEMeoA3NftQry2aG87HiMEpdPOwCgajUUaQjaRaDJhApcpNna1jOZhVZonEUi5PKofJ4XUFwuMLbbPR9NKDssOQVMUAA1rQa3XiSb0FabcA7Q70E6Xew3bBPdBLmvtuWSQH1xBvIUDkVM9nziwWgqEMWhrSLTMyxeSU0FSGBd0pakzkHbVmWoFxcVXQMmRZQ5hHHDk1EcQR8AWIVSmMQJgmkWgFkooI1BohYAFoaG8dw1BKfAYBACRI2DTllm4QgJEoGtd28NRIgkThmQkfluggYwKTMFIsAkGU6xSOQvUuAC+kwlwb1SO862UgBqXTjTON8kDBBBHiAA) links to the TM at https://github.com/thingweb/thingweb-playground/blob/master/packages/core/examples/tms/valid/optional.json where the event is not optional. However, the validation still passes

2022-12-28 10:50 UTC, egekorkan commented
I had to fix some of the examples and the corresponding expected test results. It is looking good now! :)

2022-12-28 10:50 UTC, merged